import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import { Analytics } from '@vercel/analytics/next';
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next"

const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Meet-ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>

        <html lang="en">
          <body
            className={`${inter.className} antialiased`}
          >
            <Toaster />
            {children}
            <Analytics />
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
  );
}
